'use strict';
const WORKS={
 'Paraty Club Residence':{blocks:12,phase:'Acabamento'},'Park Rubi':{blocks:19,phase:'Pós-obra'},'Atenas':{blocks:22,phase:'Acabamento'},'Aurora':{blocks:15,phase:'Fase cinza'},'Mirantes do Lago':{blocks:66,phase:'Fase cinza',modules:true},'Costa Brava':{blocks:20,phase:''},'Costa Rica':{blocks:20,phase:''}
};
const MODULES=[{name:'Módulo 1',start:1,end:16},{name:'Módulo 2',start:17,end:32},{name:'Módulo 3',start:33,end:49},{name:'Módulo 4',start:50,end:66}];
const SERVICES=['Pintura interna','Pintura externa','Cerâmica de piso','Cerâmica de parede','Rejunte e PU','Estuque','Reboco e requadração','Gesso cola','Gesso acartonado','Alvenaria','Forma','Serralheria','Guarda-corpo','Corrimão','Estrutura de telhado','Telhamento','Infra I','Infra II','Prumadas','GLP','Esquadrias','Portas de madeira','Porta postigo','Louças e metais','Bancadas','Impermeabilização','Limpeza','Outro'];
const ENVIRONMENTS=['Sala','Cozinha','Área de serviço','Quarto 1','Quarto 2','Quarto 3','Banheiro','Suíte','Varanda','Circulação','Escada','Hall','Fachada','Cobertura','Garagem','Área comum','Guarita','Outro'];
const DB_NAME='bm_diario_v4',STORE='diaries';let db,current=null,pendingPhotos=[];
const $=id=>document.getElementById(id);const today=()=>new Date().toISOString().slice(0,10);const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function showScreen(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0);if(id==='history')renderHistory()}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{const s=r.result.createObjectStore(STORE,{keyPath:'id'});s.createIndex('updatedAt','updatedAt')};r.onsuccess=()=>{db=r.result;res()};r.onerror=()=>rej(r.error)})}
function putDiary(d){d.updatedAt=new Date().toISOString();return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).put(d);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function getAll(){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function getOne(id){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function removeOne(id){return new Promise((res,rej)=>{const r=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function populate(){Object.keys(WORKS).forEach(w=>{$('obra').add(new Option(w,w));$('historyWork').add(new Option(w,w))});MODULES.forEach(m=>$('modulo').add(new Option(m.name,m.name)));SERVICES.forEach(v=>$('servico').add(new Option(v,v)));ENVIRONMENTS.forEach(v=>$('ambiente').add(new Option(v,v)));['Térreo','1º pavimento','2º pavimento','3º pavimento','4º pavimento','Cobertura','Área externa'].forEach(v=>$('pavimento').add(new Option(v,v)));$('apartamento').add(new Option('Área comum / sem apartamento',''));for(let p=1;p<=4;p++)for(let n=1;n<=4;n++){const a=`${p}0${n}`;$('apartamento').add(new Option(a,a))}}
function onWorkChange(){const name=$('obra').value,w=WORKS[name];$('moduleWrap').classList.toggle('hidden',!w.modules);if(!current?.header?.fase)$('fase').value=w.phase||'';populateBlocks()}
function populateBlocks(){const w=WORKS[$('obra').value];$('bloco').innerHTML='';let a=1,b=w.blocks;if(w.modules){const m=MODULES.find(x=>x.name===$('modulo').value)||MODULES[0];a=m.start;b=m.end}for(let i=a;i<=b;i++)$('bloco').add(new Option(`Bloco ${String(i).padStart(2,'0')}`,String(i).padStart(2,'0')))}
function updateWeekday(){if(!$('data').value)return $('diaSemana').value='';const d=new Date($('data').value+'T12:00:00');$('diaSemana').value=['Domingo','Segunda-feira','Terça-feira','Quarta-feira','Quinta-feira','Sexta-feira','Sábado'][d.getDay()]}
function newDiary(){current={id:uid(),status:'Em andamento',header:{},records:[],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};fillForm();showScreen('diary')}
function readHeader(){return{obra:$('obra').value,modulo:WORKS[$('obra').value].modules?$('modulo').value:'',data:$('data').value,fase:$('fase').value.trim(),qualidade:$('qualidade').value.trim(),engenheiro:$('engenheiro').value.trim(),encarregado:$('encarregado').value.trim(),observacaoGeral:$('observacaoGeral').value.trim()}}
async function saveHeader(silent=false){if(!current)newDiary();current.header=readHeader();await putDiary(current);$('saveStatus').textContent=`Salvo em ${new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`;if(!silent)toast('Dados do diário salvos')}
function fillForm(){const h=current?.header||{};$('obra').value=h.obra||Object.keys(WORKS)[0];$('modulo').value=h.modulo||'Módulo 2';onWorkChange();$('data').value=h.data||today();updateWeekday();$('fase').value=h.fase||WORKS[$('obra').value].phase||'';$('qualidade').value=h.qualidade||'Elvis Lima';$('engenheiro').value=h.engenheiro||'';$('encarregado').value=h.encarregado||'';$('observacaoGeral').value=h.observacaoGeral||'';renderRecords()}
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function compressImage(file){return new Promise((res,rej)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);res(c.toDataURL('image/jpeg',.78))};img.onerror=()=>{URL.revokeObjectURL(url);rej(new Error('Imagem inválida'))};img.src=url})}
async function previewPhotos(){pendingPhotos=[];$('photoPreview').innerHTML='';for(const f of [...$('fotos').files].slice(0,8)){try{const data=await compressImage(f);pendingPhotos.push(data);$('photoPreview').insertAdjacentHTML('beforeend',`<img src="${data}" alt="Prévia">`)}catch(e){toast(e.message)}}}
async function addRecord(){if(!current){toast('Crie um diário primeiro');return}const text=$('descricao').value.trim();if(!text&&!pendingPhotos.length){toast('Informe a descrição ou adicione uma foto');return}await saveHeader(true);current.records.push({id:uid(),bloco:$('bloco').value,pavimento:$('pavimento').value,apartamento:$('apartamento').value,ambiente:$('ambiente').value,servico:$('servico').value,responsavel:$('responsavelReg').value.trim(),status:$('statusReg').value,prazo:$('prazo').value,descricao:text,photos:[...pendingPhotos],createdAt:new Date().toISOString()});await putDiary(current);$('descricao').value='';$('responsavelReg').value='';$('prazo').value='';$('fotos').value='';pendingPhotos=[];$('photoPreview').innerHTML='';renderRecords();toast('Ocorrência salva')}
function recordLocation(r){return[`Bloco ${r.bloco}`,r.pavimento,r.apartamento?`Apto. ${r.apartamento}`:'',r.ambiente].filter(Boolean).join(' • ')}
function renderRecords(){const list=$('recordList');if(!current?.records?.length){list.innerHTML='<div class="empty">Nenhuma ocorrência registrada.</div>';return}list.innerHTML=current.records.map((r,i)=>`<article class="list-item"><div class="list-head"><div><strong>${i+1}. ${escapeHtml(r.servico)}</strong><div class="muted">${escapeHtml(recordLocation(r))}</div></div><button class="danger" data-delete-record="${r.id}">Excluir</button></div><div class="chips"><span class="chip">${escapeHtml(r.status)}</span>${r.responsavel?`<span class="chip">${escapeHtml(r.responsavel)}</span>`:''}${r.prazo?`<span class="chip">Prazo: ${formatDate(r.prazo)}</span>`:''}</div>${r.descricao?`<p>${escapeHtml(r.descricao)}</p>`:''}${r.photos?.length?`<div class="photo-grid">${r.photos.map(p=>`<img src="${p}" alt="Foto da ocorrência">`).join('')}</div>`:''}</article>`).join('')}
async function deleteRecord(id){if(!confirm('Excluir esta ocorrência?'))return;current.records=current.records.filter(r=>r.id!==id);await putDiary(current);renderRecords();toast('Ocorrência excluída')}
async function finishDiary(){await saveHeader(true);current.status='Finalizado';await putDiary(current);toast('Diário finalizado e salvo');showScreen('history')}
function formatDate(v){if(!v)return'';const [y,m,d]=v.split('-');return`${d}/${m}/${y}`}
async function renderHistory(){const all=(await getAll()).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),q=$('historySearch').value.toLowerCase(),w=$('historyWork').value;const filtered=all.filter(d=>{const text=JSON.stringify(d).toLowerCase();return(!q||text.includes(q))&&(!w||d.header?.obra===w)});$('historyList').innerHTML=filtered.length?filtered.map(d=>`<article class="list-item"><div class="list-head"><div><strong>${escapeHtml(d.header?.obra||'Diário sem obra')}</strong><div class="muted">${formatDate(d.header?.data)} • ${d.records?.length||0} ocorrência(s) • ${escapeHtml(d.status||'Em andamento')}</div></div><div class="actions"><button data-open="${d.id}">Abrir</button><button class="danger" data-delete-diary="${d.id}">Excluir</button></div></div></article>`).join(''):'<div class="empty">Nenhum diário encontrado.</div>'}
async function openDiary(id){current=await getOne(id);fillForm();showScreen('diary')}
async function deleteDiary(id){if(!confirm('Excluir o diário inteiro?'))return;await removeOne(id);renderHistory();toast('Diário excluído')}
async function exportBackup(){const data=await getAll(),blob=new Blob([JSON.stringify({version:4,exportedAt:new Date().toISOString(),diaries:data},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`backup-bm-diario-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
async function importBackup(file){try{const raw=JSON.parse(await file.text()),items=Array.isArray(raw)?raw:raw.diaries;if(!Array.isArray(items))throw new Error('Backup inválido');for(const d of items)await putDiary(d);toast(`${items.length} diário(s) importado(s)`);renderHistory()}catch(e){toast(e.message)}}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('button,[data-screen]');if(!b)return;if(b.dataset.screen)showScreen(b.dataset.screen);if(b.dataset.action==='new')newDiary();if(b.dataset.action==='save-header')saveHeader();if(b.dataset.action==='add-record')addRecord();if(b.dataset.action==='finish')finishDiary();if(b.dataset.action==='export-backup')exportBackup();if(b.dataset.open)openDiary(b.dataset.open);if(b.dataset.deleteRecord)deleteRecord(b.dataset.deleteRecord);if(b.dataset.deleteDiary)deleteDiary(b.dataset.deleteDiary)});$('obra').addEventListener('change',onWorkChange);$('modulo').addEventListener('change',populateBlocks);$('data').addEventListener('change',updateWeekday);$('fotos').addEventListener('change',previewPhotos);$('historySearch').addEventListener('input',renderHistory);$('historyWork').addEventListener('change',renderHistory);$('backupFile').addEventListener('change',e=>e.target.files[0]&&importBackup(e.target.files[0]))}
async function init(){populate();bind();await openDB();newDiary();showScreen('home');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
init().catch(e=>{console.error(e);alert('Falha ao iniciar o aplicativo: '+e.message)});
